sudo: false
language: ruby
script: 'bundle exec rake'
rvm:
  - 2.5.1
before_install:
  - gem install bundler -v 1.16.1
notifications:
  email:
    recipients:
      - tomas.celizna@gmail.com
      - a@asgerbehnckejacobsen.dk
    on_failure: change
    on_success: never

matrix:
  include:
    - rvm: 2.3.3
      env: MONGOID_VERSION=6
    - rvm: 2.5.1
      env: MONGOID_VERSION=7
